### ISSUE TITLE
Copy metadata/hitsound to a difficulty while opening it in the editor causes an absurdly large file size

### ISSUE THREAD

**Issue by Ryuusei-Aika** [OliBomby/Mapping_Tools#55] opened 2019-10-13 11:43 UTC
For the information: I'm using **Windows 10 Professional ver. 1809**, and the Mapping Tools is **ver. 1.3.0.0**.
([Map](https://osu.ppy.sh/beatmapsets/1048140) in case you need it)

When I tried to copy hitsounds / metadata by using hitsound copier / metadata manager with a diff opening in the editor, they have randomly added many zeros in the [Hitobjects] section:
![image](https://user-images.githubusercontent.com/52080494/66715057-6f329d00-edf1-11e9-893a-cf9e8caa0c2a.png)
And it results in an absurdly large file size: (sorry it is in chinese but I believe you can get me)
![image](https://user-images.githubusercontent.com/52080494/66715083-9d17e180-edf1-11e9-8a0a-d7c56224394a.png)

**Comment by OliBomby** [comment] 2019-10-14 10:00
From what I see in the screenshot, the length doesn't seem to be the only issue. All the objects have an absurd coordinate and time value and some sliders have 0 length.

Hitsound Copier and Metadata Manager also don't touch hitobjects all that much, so I think there's something wrong with the beatmap IO.

**Comment by OliBomby** [comment] 2019-10-14 10:08
You say this only happens when you have the editor open with the beatmap you are copying to? It works completely fine when you don't have the editor open?

**Comment by Ryuusei-Aika** [comment] 2019-10-14 10:35
Yes, But this seems quite random (for some maps, both the hitsound copier and metadata manager work fine even with a certain diff in the set opening in the editor) 
So I'm doubting if that is caused by the file name of the map itself (because the map in question was created by me, so the file name just inherited the name of my .mp3 file instead of having a set number at its beginning)

**Comment by OliBomby** [comment] 2019-10-14 16:48
I can't recreate the bug on my laptop, so I'm gonna assume it's a problem with editor reader. Next update will have an option to disable editor reader if it doesn't work on your pc for some reason. I might also add some sanity checks to see if what editor reader does makes sense.

**Comment by Karoo13** [comment] 2019-10-14 18:04
Which diff is open in the editor, the one you are copying from or copying to?

**Comment by Ryuusei-Aika** [comment] 2019-10-14 18:19
The one I'm copying to.

**Comment by Karoo13** [comment] 2019-10-14 19:46
It sounds like an issue with the memory reading (which I am responsible for), where the game is taking a while to dispose of an older editor instance. 

It should be a rare random occurrence when opening and closing the editor more than once, but if you are able to get this behavior consistently, please explain in detail what steps you are doing. 

Otherwise, I will look into a fast way to detect multiple editor instances, it is currently not detected because it would take a few seconds every time the map is read.

**Comment by Ryuusei-Aika** [comment] 2019-10-15 12:58
Well, I can't recreate that bug? anymore, but hours ago when I was trying to copy a complex timing to all diffs without open any of them, one of the .osu file becomes 10+ Mb again:
![image](https://user-images.githubusercontent.com/52080494/66833471-78a53c00-ef8e-11e9-9709-f4ac398e18aa.png)
So yes, maybe that is just an I/O problem or something...

**Comment by OliBomby** [comment] 2019-10-15 13:33
I dont know if it will be possible to fix this issue if it's this inconsistent and I can't reproduce it. I can't see all the internal values that could give a hint to where the problem could be.

The only option I see would be to log absolutely everything to some debug file so you can find the relevant information afterwards.

**Comment by Karoo13** [comment] 2019-10-15 17:28
I think what you said confirms my previous comment, I will have to find a way to distinguish partially disposed editors from the active one.

**Comment by Lehepuhur** [comment] 2019-10-23 15:15
I also got the same issue with the Slider Completionator.
Eventually got an Out Of Memory exception after a few minutes of getting large file sizes repeatedly.
![mapping tools are you ok](https://user-images.githubusercontent.com/49871077/67407398-1b2d7280-f5c0-11e9-92f6-c74ba3660f66.png)

**Comment by OliBomby** [comment] 2019-10-30 19:53
Yo i think i fixed this with the latest commit. There might still be a tiny chance it does weird stuff, but at least it shouldn't create huge files anymore. 
Coming in the next update.

**Closed as completed by OliBomby** 2019-10-30 19:53 UTC
