### ISSUE TITLE
Sliderator "Import sliders" button gives an error message saying "Editor memory was not read. Could not get the selected hit objects."

### ISSUE THREAD

**Issue by Jarran2R** [OliBomby/Mapping_Tools#88] opened 2020-02-22 03:35 UTC
It says this a lot and it fixes temporarily if i restart both the game and Mapping Tools.

**Comment by OliBomby** [comment] 2020-02-22 11:30
This problem has been here for some time.
Editor Reader, the library that lets us read the memory of the osu! editor, works on a lot of assumptions about the layout of osu! client memory and I don't really know much about how it works because it was made by Karoo.
We think the osu! client memory can randomly change and we don't know how to reproduce it, so fixing it is really hard.
I made sure to warn the user when this happens.

If you can make a memory dump of your osu! client the next time it happens to you, then it will help us a lot for fixing this problem in the future. I never get the problem myself.

**Comment by OliBomby** [comment] 2020-03-12 12:11
Karoo is working on a fix

**Comment by OliBomby** [comment] 2020-05-13 18:58
Me and Karoo managed to find the issue and Karoo fixed it. Hopefully that what we found was the bug that was bugging everyone. It has been fixed in update 1.6.5.0

**Closed as completed by OliBomby** 2020-05-13 18:58 UTC
Labels: bug
